### ISSUE TITLE
Adding catalog to Rancher

### ISSUE THREAD

**Issue by ashishkurian** [pnnl-miscscripts/miscscripts#16]
Hello There. I found this helm chart and it is very interesting for me. What I need to do is to add this repo as a custom catalog into rancher and install the helm chart to the cluster from the rancher UI.

When I deploy the chart, I get the following error

![image](https://user-images.githubusercontent.com/16349403/92151356-46f4c800-ee21-11ea-919b-4cd105ecfb46.png)

Can you help me with this?

**Comment by kfox1111** [comment]
Did you add the helm repo or the github git repo? The former should work. the latter is just the source code and doesn't have the dependencies checked in.

https://pnnl-miscscripts.github.io/charts should work

**Comment by ashishkurian** [comment]
I think I added the github repo. I will try adding the helm repo. However,
when I tried to open the helm repo, I am getting 404 error.

**Comment by kfox1111** [comment]
yeah. I think it 404's in the browser, but helm looks for certain things underneath that exist.

**Comment by ashishkurian** [comment]
@kfox1111 : Thank you for your update. I added the helm repo and it started with deploying a dhcpd pod on all of my 3 nodes. However, I got this below error. Do you know what could be wrong here?
![image](https://user-images.githubusercontent.com/16349403/92204121-12195d00-ee83-11ea-9434-edcb85c8945e.png)

**Comment by ashishkurian** [comment]
@kfox1111 : Never mind the above post. I think it is due to some error in the dhcpd configuration that I am providing to the deployment.

In the config map for dhcpd.conf I am giving the following configuration according to my cluster setup.

```
default-lease-time 600;
max-lease-time 7200;
ddns-update-style none;

interfaces cni0;

subnet 10.42.0.0 netmask 255.255.255.0 {
}
group {
  option routers 10.42.0.1;
  option domain-name "ashishkurian.com";
  option domain-name-servers 10.42.0.1;
  option subnet-mask 255.255.255.0;
  host master {
    hardware ethernet 62:7a:96:7a:4f:d4;
    fixed-address 10.42.0.1;
  }
  host agent2 {
    hardware ethernet 8e:7c:45:05:fb:76;
    fixed-address 10.42.2.1;
  }
  host agent1 {
    hardware ethernet e2:6a:7f:1b:65:27;
    fixed-address 10.42.1.1;
  }
}
```
However when I check the logs of the pod, I get the below error.
![image](https://user-images.githubusercontent.com/16349403/92223634-06d52a00-eea1-11ea-97b6-3e85ed3f60cd.png)

How should I be specifying the interface correctly?

Note : While I was playing the configuration, at some point I saw that the pod was successfully deployed on my k3os master node. But when I deleted it and when it automatically retried, it started failing.

**Comment by ashishkurian** [comment]
@kfox1111 : Never mind the above post. The error was due to an error in my config file. With the below config file, I am able to deploy it to my kluster.

```
interfaces ;

default-lease-time 600;
max-lease-time 7200;
ddns-update-style none;

subnet 10.42.0.0 netmask 255.255.0.0 {
}
group {
  option routers 10.42.0.1;
  option domain-name "ashishkurian.com";
  option domain-name-servers 10.42.0.1;
  option subnet-mask 255.255.0.0;
  host master {
    hardware ethernet 62:7a:96:7a:4f:d4;
    fixed-address 10.42.0.1;
  }
  host agent2 {
    hardware ethernet 8e:7c:45:05:fb:76;
    fixed-address 10.42.2.1;
  }
  host agent1 {
    hardware ethernet e2:6a:7f:1b:65:27;
    fixed-address 10.42.1.1;
  }
}
```

**Comment by ashishkurian** [comment]
One question : When I deploy the chart using Rancher, it is not asking me to provide my configuration file. How I deploy is a little complicated. First I deploy and it will error out. Then I get the option to edit the config map that was applied to the chart and then I edit the chart with a the correct config. Then the app deploys correctly.

Do you know how I can specify the config file while installing the chart?

**Comment by kfox1111** [comment]
I don't know much about Rancher unfortunately. I usually drive helm directly through CI/CD.

It's odd that it doesn't know to configure it during the first install but does during upgrade. That seems like a bug in Rancher.

Glad you were able to get it working. :)
