### ISSUE TITLE
Unable to install chronyd helm-chart: unknown field "resources"

### ISSUE THREAD

**Issue by k8s-ninja** [pnnl-miscscripts/miscscripts#6]
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec): unknown field "resources" in io.k8s.api.core.v1.PodSpec

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.1", GitCommit:"aa93664bafe74f3c051e021b27a64e28ac34ab40", GitTreeState:"clean", BuildDate:"2020-03-18T22:49:35Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

Could be resources in the wrong place? (It should be in container section)

**Comment by kfox1111** [comment]
Good catch. It should be fixed now in trunk and there is a new release. Don't forget to:
```
helm repo update
```

Thanks!
Kevin
